name: TikTok Notifier

on:
  schedule:
    - cron: '*/30 * * * *' # Jalan otomatis tiap 30 menit
  workflow_dispatch: # Bisa dijalankan manual lewat tombol di GitHub

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cek TikTok & Kirim Notif
        run: python main.py

      - name: Simpan Data Terakhir
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_video.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last_video.txt" && git push)
